# Tugas 1

In [14]:
import pandas as pd
import numpy as np

In [11]:
# Menggabungkan dua data pada excell
data1=pd.read_csv("D:\Data Mining\kebakaran1.csv", sep=";")
data2 =pd.read_csv("D:\Data Mining\kebakaran2.csv", sep=";")
data_complete=pd.merge(data1,data2, on='month')
data_complete.head()

  month  day  FFMC   DMC    DC  ISI  temp  RH wind rain area
0   mar  fri  86,2  26,2  94,3  5,1   8,2  51  6,7    0    0
1   mar  fri  86,2  26,2  94,3    9   8,3  97    4  0,2    0
2   mar  fri  86,2  26,2  94,3  9,6  11,4  99  1,8    0    0
3   mar  fri  86,2  26,2  94,3  7,8  15,1  27  5,4    0    0
4   mar  fri  86,2  26,2  94,3  6,3  15,9  35    4    0    0

In [12]:
data_complete

      month  day  FFMC   DMC     DC   ISI  temp  RH wind rain   area
0       mar  fri  86,2  26,2   94,3   5,1   8,2  51  6,7    0      0
1       mar  fri  86,2  26,2   94,3     9   8,3  97    4  0,2      0
2       mar  fri  86,2  26,2   94,3   9,6  11,4  99  1,8    0      0
3       mar  fri  86,2  26,2   94,3   7,8  15,1  27  5,4    0      0
4       mar  fri  86,2  26,2   94,3   6,3  15,9  35    4    0      0
5       mar  fri  86,2  26,2   94,3   3,8  14,1  43  2,7    0      0
6       mar  fri  86,2  26,2   94,3   4,1  11,8  35  1,8    0      0
7       mar  fri  86,2  26,2   94,3     5    11  46  5,8    0      0
8       mar  fri  86,2  26,2   94,3   9,6  11,5  39  5,8    0      0
9       mar  fri  86,2  26,2   94,3   9,6   5,5  59  6,3    0      0
10      mar  fri  86,2  26,2   94,3     9  17,2  26  4,5    0      0
11      mar  fri  86,2  26,2   94,3  12,5  15,8  27  7,6    0      0
12      mar  fri  86,2  26,2   94,3     9  15,6  25  6,3    0      0
13      mar  fri  86,2  26,2   94,3     5   8,3  72  3,1    0      0
14      mar  fri  86,2  26,2   94,3   7,8  17,4  25  4,9    0      0
15      mar  fri  86,2  26,2   94,3   7,8  17,4  24  5,4    0      0
16      mar  fri  86,2  26,2   94,3   0,7  17,4  24  5,4    0      0
17      mar  fri  86,2  26,2   94,3   2,8  12,7  52  6,3    0      0
18      mar  fri  86,2  26,2   94,3   7,5  18,2  29  3,1    0      0
19      mar  fri  86,2  26,2   94,3   2,8  13,7  43  5,8    0      0
20      mar  fri  86,2  26,2   94,3     9  18,8  18  4,5    0      0
21      mar  fri  86,2  26,2   94,3   3,8  15,8  27  7,6    0      0
22      mar  fri  86,2  26,2   94,3   3,8  15,5  27  6,3    0      0
23      mar  fri  86,2  26,2   94,3   7,8  11,6  30  6,3    0      0
24      mar  fri  86,2  26,2   94,3   7,8  15,2  27  4,9    0      0
25      mar  fri  86,2  26,2   94,3   6,2  10,6  30    4    0      0
26      mar  fri  86,2  26,2   94,3     5     9  49  2,2    0      0
27      mar  fri  86,2  26,2   94,3   4,1    14  39  3,1    0      0
28      mar  fri  86,2  26,2   94,3   9,6  10,6  46  4,9    0      0
29      mar  fri  86,2  26,2   94,3   3,8  14,9  38  2,7    0      0
...     ...  ...   ...   ...    ...   ...   ...  ..  ...  ...    ...
68435   dec  mon  85,4  25,4  349,7     2   5,1  61  4,9    0   5,38
68436   dec  mon  85,4  25,4  349,7   2,6   4,6  21  8,5    0  17,85
68437   dec  mon  85,4  25,4  349,7   2,6   4,6  21  8,5    0  10,73
68438   dec  mon  85,4  25,4  349,7   2,6   4,6  21  8,5    0  22,03
68439   dec  mon  85,4  25,4  349,7   2,6   4,6  21  8,5    0   9,77
68440   dec  mon  85,4  25,4  349,7   4,1   2,2  59  4,9    0   9,27
68441   dec  mon  85,4  25,4  349,7   2,6   5,1  24  8,5    0  24,77
68442   dec  fri  84,7  26,7  352,6   6,8   4,8  57  8,5    0   8,98
68443   dec  fri  84,7  26,7  352,6   5,3   5,1  61    8    0  11,19
68444   dec  fri  84,7  26,7  352,6     2   5,1  61  4,9    0   5,38
68445   dec  fri  84,7  26,7  352,6   2,6   4,6  21  8,5    0  17,85
68446   dec  fri  84,7  26,7  352,6   2,6   4,6  21  8,5    0  10,73
68447   dec  fri  84,7  26,7  352,6   2,6   4,6  21  8,5    0  22,03
68448   dec  fri  84,7  26,7  352,6   2,6   4,6  21  8,5    0   9,77
68449   dec  fri  84,7  26,7  352,6   4,1   2,2  59  4,9    0   9,27
68450   dec  fri  84,7  26,7  352,6   2,6   5,1  24  8,5    0  24,77
68451   dec  tue  85,4  25,4  349,7   6,8   4,8  57  8,5    0   8,98
68452   dec  tue  85,4  25,4  349,7   5,3   5,1  61    8    0  11,19
68453   dec  tue  85,4  25,4  349,7     2   5,1  61  4,9    0   5,38
68454   dec  tue  85,4  25,4  349,7   2,6   4,6  21  8,5    0  17,85
68455   dec  tue  85,4  25,4  349,7   2,6   4,6  21  8,5    0  10,73
68456   dec  tue  85,4  25,4  349,7   2,6   4,6  21  8,5    0  22,03
68457   dec  tue  85,4  25,4  349,7   2,6   4,6  21  8,5    0   9,77
68458   dec  tue  85,4  25,4  349,7   4,1   2,2  59  4,9    0   9,27
68459   dec  tue  85,4  25,4  349,7   2,6   5,1  24  8,5    0  24,77
68460   may  sat  85,1    28  113,8   3,5  11,3  94  4,9    0      0
68461   may  sat  85,1    28  113,8   5,7    18  40    4    0  38,48
68462   may  fri  89,6  25,4   73,7   3,5  11,3  94  4,9    0      0
68463   may  fri  89,6  25,4   73,7   5,7    18  40    4    0  38,48
68464   nov  tue  79,5     3  106,7   1,1  11,8  31  4,5    0      0

[68465 rows x 11 columns]

In [13]:
# Menyimpan excell langsung ke file
data_complete.to_csv("D:/Data Mining/data_kebakaran.csv")

In [10]:
data1

    month  day  FFMC    DMC     DC
0     mar  fri  86,2   26,2   94,3
1     oct  tue  90,6   35,4  669,1
2     oct  sat  90,6   43,7  686,9
3     mar  fri  91,7   33,3   77,5
4     mar  sun  89,3   51,3  102,2
5     aug  sun  92,3   85,3    488
6     aug  mon  92,3   88,9  495,6
7     aug  mon  91,5  145,4  608,2
8     sep  tue    91  129,5  692,6
9     sep  sat  92,5     88  698,6
10    sep  sat  92,5     88  698,6
11    sep  sat  92,8   73,2    713
12    aug  fri  63,5   70,8  665,3
13    sep  mon  90,9  126,5  686,5
14    sep  wed  92,9  133,3  699,6
15    sep  fri  93,3  141,2  713,9
16    mar  sat  91,7   35,8   80,8
17    oct  mon  84,9   32,8  664,2
18    mar  wed  89,2   27,9   70,8
19    apr  sat  86,3   27,4   97,1
20    sep  tue    91  129,5  692,6
21    sep  mon  91,8   78,5  724,3
22    jun  sun  94,3   96,3    200
23    aug  sat  90,2  110,9  537,4
24    aug  sat  93,5  139,4  594,2
25    aug  sun  91,4  142,4  601,4
26    sep  fri  92,4  117,9    668
27    sep  mon  90,9  126,5  686,5
28    sep  sat  93,4  145,4  721,4
29    sep  sun  93,5  149,3  728,6
..    ...  ...   ...    ...    ...
487   aug  tue  95,1  141,3  605,8
488   aug  tue  95,1  141,3  605,8
489   aug  wed  95,1  141,3  605,8
490   aug  wed  95,1  141,3  605,8
491   aug  thu  95,8    152  624,1
492   aug  fri  95,9    158  633,6
493   aug  fri  95,9    158  633,6
494   aug  sat    96    164    643
495   aug  mon  96,2  175,5  661,8
496   aug  mon  96,2  175,5  661,8
497   aug  tue  96,1  181,1  671,2
498   aug  tue  96,1  181,1  671,2
499   aug  tue  96,1  181,1  671,2
500   aug  tue  96,1  181,1  671,2
501   aug  tue  96,1  181,1  671,2
502   aug  tue  96,1  181,1  671,2
503   aug  wed  94,5  139,4  689,1
504   aug  wed  94,5  139,4  689,1
505   aug  thu    91  163,2  744,4
506   aug  fri    91  166,9  752,6
507   aug  fri    91  166,9  752,6
508   aug  fri    91  166,9  752,6
509   aug  fri    91  166,9  752,6
510   aug  fri    91  166,9  752,6
511   aug  sun  81,6   56,7  665,6
512   aug  sun  81,6   56,7  665,6
513   aug  sun  81,6   56,7  665,6
514   aug  sun  81,6   56,7  665,6
515   aug  sat  94,4    146  614,7
516   nov  tue  79,5      3  106,7

[517 rows x 5 columns]

In [8]:
data2

    month   ISI  temp  RH wind rain   area
0     mar   5,1   8,2  51  6,7    0      0
1     oct   6,7    18  33  0,9    0      0
2     oct   6,7  14,6  33  1,3    0      0
3     mar     9   8,3  97    4  0,2      0
4     mar   9,6  11,4  99  1,8    0      0
5     aug  14,7  22,2  29  5,4    0      0
6     aug   8,5  24,1  27  3,1    0      0
7     aug  10,7     8  86  2,2    0      0
8     sep     7  13,1  63  5,4    0      0
9     sep   7,1  22,8  40    4    0      0
10    sep   7,1  17,8  51  7,2    0      0
11    sep  22,6  19,3  38    4    0      0
12    aug   0,8    17  72  6,7    0      0
13    sep     7  21,3  42  2,2    0      0
14    sep   9,2  26,4  21  4,5    0      0
15    sep  13,9  22,9  44  5,4    0      0
16    mar   7,8  15,1  27  5,4    0      0
17    oct     3  16,7  47  4,9    0      0
18    mar   6,3  15,9  35    4    0      0
19    apr   5,1   9,3  44  4,5    0      0
20    sep     7  18,3  40  2,7    0      0
21    sep   9,2  19,1  38  2,7    0      0
22    jun  56,1    21  44  4,5    0      0
23    aug   6,2  19,5  43  5,8    0      0
24    aug  20,3  23,7  32  5,8    0      0
25    aug  10,6  16,3  60  5,4    0      0
26    sep  12,2    19  34  5,8    0      0
27    sep     7  19,4  48  1,3    0      0
28    sep   8,1  30,2  24  2,7    0      0
29    sep   8,1  22,8  39  3,6    0      0
..    ...   ...   ...  ..  ...  ...    ...
487   aug  17,7  26,4  34  3,6    0   16,4
488   aug  17,7  19,4  71  7,6    0   46,7
489   aug  17,7  20,6  58  1,3    0      0
490   aug  17,7  28,7  33    4    0      0
491   aug  13,8  32,4  21  4,5    0      0
492   aug  11,3  32,4  27  2,2    0      0
493   aug  11,3  27,5  29  4,5    0  43,32
494   aug    14  30,8  30  4,9    0   8,59
495   aug  16,8  23,9  42  2,2    0      0
496   aug  16,8  32,6  26  3,1    0   2,77
497   aug  14,3  32,3  27  2,2    0  14,68
498   aug  14,3  33,3  26  2,7    0  40,54
499   aug  14,3  27,3  63  4,9  6,4  10,82
500   aug  14,3  21,6  65  4,9  0,8      0
501   aug  14,3  21,6  65  4,9  0,8      0
502   aug  14,3  20,7  69  4,9  0,4      0
503   aug    20  29,2  30  4,9    0   1,95
504   aug    20  28,9  29  4,9    0  49,59
505   aug  10,1  26,7  35  1,8    0    5,8
506   aug   7,1  18,5  73  8,5    0      0
507   aug   7,1  25,9  41  3,6    0      0
508   aug   7,1  25,9  41  3,6    0      0
509   aug   7,1  21,1  71  7,6  1,4   2,17
510   aug   7,1  18,2  62  5,4    0   0,43
511   aug   1,9  27,8  35  2,7    0      0
512   aug   1,9  27,8  32  2,7    0   6,44
513   aug   1,9  21,9  71  5,8    0  54,29
514   aug   1,9  21,2  70  6,7    0  11,16
515   aug  11,3  25,6  42    4    0      0
516   nov   1,1  11,8  31  4,5    0      0

[517 rows x 7 columns]