# Latihan

In [3]:
import pandas as pd
import numpy as np

In [5]:
#import dataset
pcademo=pd.read_csv("D:\pcademo.csv")
x=pcademo.iloc[0:51,1:20]
x.tail()

,Census Resident Total Population - Apr-1-2000,Resident Total Population Estimate - Jul-1-2000,Resident Total Population Estimate - Jul-1-2001,Net Domestic Migration - Jul-1-2000,Net Domestic Migration - Jul-1-2001,Federal/Civilian Movement from Abroad - Jul-1-2000,Federal/Civilian Movement from Abroad - Jul-1-2001,Net International Migration - Jul-1-2000,Net International Migration - Jul-1-2001,Period Births - Jul-1-2000,Period Births - Jul-1-2001,Period Deaths - Jul-1-2000,Period Deaths - Jul-1-2001,Resident Under 65 Population Estimate - Jul-1-2000,Resident Under 65 Population Estimate - Jul-1-2001,Resident 65 Plus Population Estimate - Jul-1-2000,Resident 65 Plus Population Estimate - Jul-1-2001,Residual - Jul-1-2000,Residual - Jul-1-2001
46,7078515.0,7104016.0,7187734.0,8119.0,18299.0,232.0,-1212.0,5721.0,22619.0,24352.0,100188.0,13158.0,57337.0,6308235.0,6380181.0,795781.0,807553.0,235.0,1161.0
47,5894121.0,5908372.0,5987973.0,425.0,21995.0,83.0,-444.0,5249.0,22052.0,19388.0,80339.0,10365.0,44681.0,5244172.0,5317341.0,664200.0,670632.0,-529.0,340.0
48,1808344.0,1807099.0,1801916.0,-1411.0,-4442.0,0.0,-1.0,129.0,491.0,5041.0,20436.0,4937.0,21435.0,1530334.0,1526360.0,276765.0,275556.0,-67.0,-232.0
49,5363675.0,5372243.0,5401906.0,1536.0,2974.0,0.0,-5.0,1571.0,6056.0,16696.0,68631.0,11058.0,47276.0,4669153.0,4698404.0,703090.0,703502.0,-177.0,-717.0
50,493782.0,494001.0,494423.0,-399.0,-2041.0,5.0,-27.0,100.0,390.0,1480.0,6130.0,976.0,3980.0,436178.0,436217.0,57823.0,58206.0,9.0,-50.0

In [8]:
#normalization
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') #default norm l2, other are l1 and max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
46,0.462700,0.464367,0.469840,0.000531,0.001196,0.000015,-7.922467e-05,0.000374,0.001479,0.001592,0.006549,0.000860,0.003748,0.412350,0.417053,0.052018,0.052787,0.000015,0.000076
47,0.462826,0.463946,0.470196,0.000033,0.001727,0.000007,-3.486439e-05,0.000412,0.001732,0.001522,0.006308,0.000814,0.003509,0.411790,0.417536,0.052155,0.052660,-0.000042,0.000027
48,0.473139,0.472813,0.471457,-0.000369,-0.001162,0.000000,-2.616422e-07,0.000034,0.000128,0.001319,0.005347,0.001292,0.005608,0.400400,0.399360,0.072413,0.072097,-0.000018,-0.000061
49,0.467409,0.468156,0.470741,0.000134,0.000259,0.000000,-4.357173e-07,0.000137,0.000528,0.001455,0.005981,0.000964,0.004120,0.406886,0.409435,0.061270,0.061306,-0.000015,-0.000062
50,0.466655,0.466862,0.467261,-0.000377,-0.001929,0.000005,-2.551669e-05,0.000095,0.000369,0.001399,0.005793,0.000922,0.003761,0.412216,0.412252,0.054646,0.055008,0.000009,-0.000047

In [10]:
#minmax
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(-5,1))
scaler.fit(x) #rumus bawaan packcage Minmaxscaler
x_scaled=scaler.transform(x)
x_scaled=pd.DataFrame(x_scaled)
x_scaled.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
46,-3.816329,-3.816344,-3.819060,-0.837422,-1.735456,-0.857143,-3.799207,-4.529964,-4.508216,-3.930357,-3.923450,-3.596840,-3.573392,-3.823774,-3.827188,-3.724622,-3.722345,-1.816967,-1.375883
47,-4.029236,-4.030448,-4.030741,-1.443074,-1.681392,-3.517857,-0.755614,-4.569434,-4.520748,-4.162506,-4.150634,-3.910890,-3.905361,-4.036916,-4.036899,-3.945483,-3.949331,-4.480535,-2.267789
48,-4.763695,-4.764864,-4.769311,-1.587599,-2.068107,-5.000000,1.000000,-4.997575,-4.997281,-4.833465,-4.836259,-4.521223,-4.515109,-4.780831,-4.784902,-4.595799,-4.604285,-2.869843,-2.889191
49,-4.124589,-4.126453,-4.134144,-1.355619,-1.959627,-5.000000,0.984148,-4.876993,-4.874286,-4.288401,-4.284639,-3.832968,-3.837294,-4.152097,-4.159022,-3.880205,-3.894840,-3.253341,-3.416078
50,-5.000000,-5.000000,-5.000000,-1.507937,-2.032986,-4.910714,0.896962,-5.000000,-4.999514,-5.000000,-5.000000,-4.966605,-4.972957,-5.000000,-5.000000,-4.963298,-4.964606,-2.604881,-2.691472

In [14]:
#3sigmoid
xsigmoidal=((1-2.718281828**(-xnorm))/(1+2.718281828**(-xnorm)))
xsigmoidal=pd.DataFrame(xsigmoidal)
xsigmoidal.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
46,0.227309,0.228099,0.230692,0.000265,0.000598,0.000008,-3.961233e-05,0.000187,0.000739,0.000796,0.003274,0.000430,0.001874,0.203302,0.205555,0.026003,0.026387,0.000008,0.000038
47,0.227369,0.227899,0.230860,0.000017,0.000864,0.000003,-1.743220e-05,0.000206,0.000866,0.000761,0.003154,0.000407,0.001754,0.203034,0.205787,0.026072,0.026324,-0.000021,0.000013
48,0.232253,0.232099,0.231457,-0.000185,-0.000581,0.000000,-1.308211e-07,0.000017,0.000064,0.000659,0.002673,0.000646,0.002804,0.197567,0.197068,0.036191,0.036033,-0.000009,-0.000030
49,0.229541,0.229894,0.231118,0.000067,0.000130,0.000000,-2.178586e-07,0.000068,0.000264,0.000727,0.002990,0.000482,0.002060,0.200682,0.201905,0.030625,0.030643,-0.000008,-0.000031
50,0.229183,0.229282,0.229470,-0.000189,-0.000964,0.000002,-1.275835e-05,0.000047,0.000184,0.000699,0.002897,0.000461,0.001881,0.203238,0.203256,0.027316,0.027497,0.000004,-0.000024

In [15]:
#decimal scalling
xdecimal=x/(10**3) #rumus asli x/(10**i) , i dapat ditentukan dg bebas
xdecimal=pd.DataFrame(xdecimal)
xdecimal.tail()

,Census Resident Total Population - Apr-1-2000,Resident Total Population Estimate - Jul-1-2000,Resident Total Population Estimate - Jul-1-2001,Net Domestic Migration - Jul-1-2000,Net Domestic Migration - Jul-1-2001,Federal/Civilian Movement from Abroad - Jul-1-2000,Federal/Civilian Movement from Abroad - Jul-1-2001,Net International Migration - Jul-1-2000,Net International Migration - Jul-1-2001,Period Births - Jul-1-2000,Period Births - Jul-1-2001,Period Deaths - Jul-1-2000,Period Deaths - Jul-1-2001,Resident Under 65 Population Estimate - Jul-1-2000,Resident Under 65 Population Estimate - Jul-1-2001,Resident 65 Plus Population Estimate - Jul-1-2000,Resident 65 Plus Population Estimate - Jul-1-2001,Residual - Jul-1-2000,Residual - Jul-1-2001
46,7078.515,7104.016,7187.734,8.119,18.299,0.232,-1.212,5.721,22.619,24.352,100.188,13.158,57.337,6308.235,6380.181,795.781,807.553,0.235,1.161
47,5894.121,5908.372,5987.973,0.425,21.995,0.083,-0.444,5.249,22.052,19.388,80.339,10.365,44.681,5244.172,5317.341,664.200,670.632,-0.529,0.340
48,1808.344,1807.099,1801.916,-1.411,-4.442,0.000,-0.001,0.129,0.491,5.041,20.436,4.937,21.435,1530.334,1526.360,276.765,275.556,-0.067,-0.232
49,5363.675,5372.243,5401.906,1.536,2.974,0.000,-0.005,1.571,6.056,16.696,68.631,11.058,47.276,4669.153,4698.404,703.090,703.502,-0.177,-0.717
50,493.782,494.001,494.423,-0.399,-2.041,0.005,-0.027,0.100,0.390,1.480,6.130,0.976,3.980,436.178,436.217,57.823,58.206,0.009,-0.050

In [16]:
#softmax
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft)

          0         1         2         3         4         5         6   \
0   0.019651  0.019641  0.019595  0.019605  0.019589  0.019608  0.019608
1   0.019390  0.019381  0.019412  0.019585  0.019590  0.019608  0.019606
2   0.019521  0.019563  0.019742  0.019638  0.019739  0.019608  0.019608
3   0.019663  0.019660  0.019636  0.019611  0.019609  0.019608  0.019608
4   0.019514  0.019529  0.019590  0.019603  0.019587  0.019608  0.019608
5   0.019450  0.019477  0.019601  0.019626  0.019691  0.019608  0.019608
6   0.019664  0.019657  0.019625  0.019604  0.019583  0.019608  0.019608
7   0.019598  0.019610  0.019653  0.019621  0.019655  0.019608  0.019608
8   0.019645  0.019611  0.019550  0.019570  0.019534  0.019608  0.019608
9   0.019685  0.019708  0.019834  0.019626  0.019724  0.019608  0.019608
10  0.019457  0.019486  0.019582  0.019628  0.019670  0.019608  0.019608
11  0.019636  0.019623  0.019642  0.019584  0.019582  0.019608  0.019606
12  0.019525  0.019544  0.019623  0.019621  0.019664  0.019608  0.019608
13  0.019613  0.019607  0.019569  0.019593  0.019538  0.019608  0.019608
14  0.019621  0.019616  0.019581  0.019607  0.019587  0.019608  0.019608
15  0.019723  0.019708  0.019622  0.019601  0.019553  0.019608  0.019608
16  0.019659  0.019652  0.019589  0.019600  0.019547  0.019608  0.019608
17  0.019624  0.019618  0.019587  0.019609  0.019607  0.019608  0.019608
18  0.019625  0.019608  0.019527  0.019593  0.019532  0.019608  0.019608
19  0.019668  0.019664  0.019662  0.019619  0.019667  0.019608  0.019608
20  0.019553  0.019559  0.019596  0.019609  0.019625  0.019608  0.019608
21  0.019660  0.019653  0.019612  0.019602  0.019575  0.019608  0.019608
22  0.019620  0.019614  0.019577  0.019604  0.019580  0.019608  0.019608
23  0.019590  0.019593  0.019597  0.019612  0.019611  0.019608  0.019608
24  0.019616  0.019611  0.019567  0.019606  0.019577  0.019608  0.019608
25  0.019652  0.019647  0.019617  0.019609  0.019605  0.019608  0.019608
26  0.019666  0.019658  0.019598  0.019610  0.019589  0.019608  0.019608
27  0.019675  0.019664  0.019594  0.019598  0.019545  0.019608  0.019608
28  0.019382  0.019454  0.019771  0.019665  0.019864  0.019608  0.019608
29  0.019555  0.019567  0.019636  0.019627  0.019705  0.019608  0.019608
30  0.019635  0.019632  0.019620  0.019599  0.019572  0.019608  0.019608
31  0.019605  0.019598  0.019565  0.019595  0.019555  0.019608  0.019608
32  0.019653  0.019641  0.019579  0.019586  0.019506  0.019608  0.019608
33  0.019564  0.019577  0.019628  0.019620  0.019655  0.019608  0.019607
34  0.019769  0.019731  0.019565  0.019581  0.019482  0.019608  0.019608
35  0.019665  0.019652  0.019591  0.019601  0.019571  0.019608  0.019608
36  0.019660  0.019648  0.019594  0.019601  0.019576  0.019608  0.019608
37  0.019597  0.019600  0.019643  0.019611  0.019653  0.019608  0.019608
38  0.019739  0.019722  0.019653  0.019602  0.019587  0.019608  0.019608
39  0.019666  0.019664  0.019668  0.019613  0.019639  0.019608  0.019608
40  0.019585  0.019593  0.019610  0.019619  0.019642  0.019608  0.019608
41  0.019693  0.019682  0.019623  0.019604  0.019573  0.019608  0.019608
42  0.019608  0.019610  0.019598  0.019615  0.019619  0.019608  0.019608
43  0.019476  0.019498  0.019589  0.019613  0.019632  0.019608  0.019608
44  0.019458  0.019473  0.019514  0.019600  0.019553  0.019608  0.019608
45  0.019629  0.019624  0.019602  0.019614  0.019631  0.019608  0.019608
46  0.019544  0.019558  0.019593  0.019618  0.019629  0.019608  0.019607
47  0.019547  0.019550  0.019600  0.019608  0.019639  0.019608  0.019608
48  0.019749  0.019724  0.019625  0.019600  0.019582  0.019608  0.019608
49  0.019637  0.019633  0.019611  0.019610  0.019610  0.019608  0.019608
50  0.019622  0.019607  0.019543  0.019600  0.019567  0.019608  0.019608

          7         8         9         10        11        12        13  \
0   0.019603  0.019591  0.019609  0.019613  0.019611  0.019622  0.019590
1   0.019607  0.019603  0.019612  0.019624  0.019599  0.019569  0.020021
2   0.019613  0.019625  0.019613  0.019629  0.019606  0.019600  0.019524
3   0.019605  0.019594  0.019609  0.019613  0.019612  0.019624  0.019522
4   0.019621  0.019657  0.019611  0.019622  0.019604  0.019589  0.019714
5   0.019610  0.019617  0.019609  0.019614  0.019603  0.019585  0.019752
6   0.019610  0.019617  0.019605  0.019596  0.019608  0.019610  0.019536
7   0.019606  0.019604  0.019608  0.019610  0.019608  0.019609  0.019568
8   0.019614  0.019637  0.019609  0.019611  0.019612  0.019626  0.019643
9   0.019618  0.019639  0.019606  0.019599  0.019611  0.019623  0.019236
10  0.019608  0.019609  0.019613  0.019629  0.019605  0.019599  0.019768
11  0.019611  0.019625  0.019611  0.019623  0.019604  0.019591  0.019551
12  0.019607  0.019605  0.019610  0.019619  0.019605  0.019595  0.019666
13  0.019614  0.019628  0.019610  0.019617  0.019608  0.019607  0.019651
14  0.019605  0.019596  0.019608  0.019609  0.019609  0.019612  0.019631
15  0.019605  0.019596  0.019606  0.019598  0.019610  0.019617  0.019479
16  0.019608  0.019605  0.019609  0.019614  0.019609  0.019613  0.019583
17  0.019604  0.019591  0.019607  0.019605  0.019610  0.019618  0.019622
18  0.019603  0.019591  0.019612  0.019623  0.019609  0.019613  0.019697
19  0.019603  0.019590  0.019600  0.019576  0.019610  0.019618  0.019487
20  0.019611  0.019622  0.019608  0.019610  0.019607  0.019604  0.019676
21  0.019609  0.019614  0.019605  0.019597  0.019608  0.019610  0.019556
22  0.019606  0.019602  0.019607  0.019605  0.019608  0.019609  0.019639
23  0.019606  0.019603  0.019607  0.019603  0.019606  0.019598  0.019638
24  0.019603  0.019589  0.019613  0.019627  0.019611  0.019621  0.019654
25  0.019605  0.019595  0.019607  0.019605  0.019611  0.019619  0.019556
26  0.019603  0.019588  0.019603  0.019589  0.019609  0.019611  0.019571
27  0.019607  0.019601  0.019608  0.019611  0.019609  0.019609  0.019563
28  0.019617  0.019645  0.019609  0.019613  0.019605  0.019595  0.019611
29  0.019604  0.019594  0.019602  0.019585  0.019606  0.019600  0.019623
30  0.019615  0.019637  0.019607  0.019601  0.019607  0.019606  0.019568
31  0.019608  0.019608  0.019610  0.019616  0.019605  0.019596  0.019675
32  0.019617  0.019647  0.019607  0.019606  0.019607  0.019605  0.019604
33  0.019607  0.019604  0.019610  0.019617  0.019608  0.019610  0.019626
34  0.019604  0.019591  0.019603  0.019590  0.019610  0.019613  0.019513
35  0.019604  0.019593  0.019607  0.019608  0.019610  0.019617  0.019579
36  0.019605  0.019598  0.019609  0.019609  0.019611  0.019621  0.019581
37  0.019609  0.019614  0.019606  0.019600  0.019608  0.019607  0.019577
38  0.019605  0.019598  0.019603  0.019589  0.019612  0.019627  0.019423
39  0.019608  0.019610  0.019603  0.019588  0.019610  0.019617  0.019476
40  0.019604  0.019595  0.019609  0.019610  0.019609  0.019613  0.019633
41  0.019603  0.019591  0.019608  0.019606  0.019610  0.019615  0.019510
42  0.019604  0.019594  0.019608  0.019608  0.019610  0.019617  0.019625
43  0.019614  0.019630  0.019615  0.019635  0.019604  0.019592  0.019747
44  0.019610  0.019614  0.019622  0.019666  0.019601  0.019578  0.019852
45  0.019604  0.019595  0.019600  0.019575  0.019607  0.019606  0.019603
46  0.019609  0.019613  0.019608  0.019608  0.019606  0.019601  0.019687
47  0.019610  0.019618  0.019607  0.019604  0.019605  0.019596  0.019676
48  0.019603  0.019587  0.019603  0.019585  0.019614  0.019637  0.019453
49  0.019605  0.019595  0.019605  0.019597  0.019608  0.019608  0.019579
50  0.019604  0.019592  0.019604  0.019594  0.019607  0.019601  0.019684

          14        15        16        17        18
0   0.019545  0.019658  0.019657  0.019608  0.019607
1   0.020046  0.018980  0.018986  0.019609  0.019608
2   0.019675  0.019646  0.019673  0.019608  0.019609
3   0.019505  0.019746  0.019738  0.019608  0.019608
4   0.019770  0.019423  0.019429  0.019608  0.019608
5   0.019868  0.019334  0.019343  0.019608  0.019610
6   0.019510  0.019729  0.019722  0.019607  0.019606
7   0.019597  0.019649  0.019663  0.019607  0.019606
8   0.019612  0.019575  0.019545  0.019608  0.019607
9   0.019347  0.020088  0.020100  0.019608  0.019610
10  0.019858  0.019327  0.019334  0.019609  0.019611
11  0.019558  0.019679  0.019692  0.019608  0.019606
12  0.019736  0.019485  0.019495  0.019609  0.019610
13  0.019623  0.019563  0.019552  0.019608  0.019609
14  0.019602  0.019592  0.019586  0.019608  0.019608
15  0.019409  0.019838  0.019822  0.019607  0.019607
16  0.019532  0.019676  0.019665  0.019608  0.019608
17  0.019595  0.019603  0.019598  0.019608  0.019607
18  0.019622  0.019518  0.019512  0.019608  0.019608
19  0.019483  0.019785  0.019786  0.019607  0.019607
20  0.019707  0.019490  0.019496  0.019608  0.019608
21  0.019523  0.019704  0.019696  0.019608  0.019606
22  0.019606  0.019582  0.019577  0.019607  0.019607
23  0.019646  0.019562  0.019558  0.019608  0.019608
24  0.019613  0.019564  0.019561  0.019608  0.019608
25  0.019535  0.019698  0.019690  0.019608  0.019608
26  0.019513  0.019693  0.019692  0.019608  0.019608
27  0.019505  0.019707  0.019697  0.019607  0.019607
28  0.019881  0.019450  0.019498  0.019610  0.019614
29  0.019686  0.019550  0.019557  0.019608  0.019608
30  0.019562  0.019672  0.019665  0.019608  0.019608
31  0.019631  0.019530  0.019541  0.019608  0.019607
32  0.019551  0.019644  0.019635  0.019608  0.019608
33  0.019669  0.019557  0.019565  0.019608  0.019608
34  0.019364  0.019826  0.019810  0.019608  0.019609
35  0.019525  0.019680  0.019673  0.019608  0.019607
36  0.019531  0.019674  0.019670  0.019608  0.019608
37  0.019619  0.019630  0.019631  0.019608  0.019607
38  0.019369  0.019908  0.019894  0.019607  0.019606
39  0.019487  0.019797  0.019788  0.019607  0.019606
40  0.019638  0.019566  0.019578  0.019608  0.019607
41  0.019461  0.019780  0.019769  0.019607  0.019608
42  0.019609  0.019592  0.019596  0.019608  0.019608
43  0.019830  0.019360  0.019368  0.019608  0.019609
44  0.019883  0.019233  0.019243  0.019608  0.019608
45  0.019578  0.019628  0.019630  0.019607  0.019606
46  0.019713  0.019479  0.019487  0.019608  0.019610
47  0.019723  0.019482  0.019485  0.019607  0.019609
48  0.019367  0.019880  0.019867  0.019608  0.019607
49  0.019563  0.019660  0.019654  0.019608  0.019607
50  0.019619  0.019530  0.019531  0.019608  0.019607

In [ ]:
#feature selection (mencari skor)
from sklearn.feature_selection import SelectKBest, chi2, f_regression
xx=x.iloc[0:50,2:20]
y=x.iloc[]